const roomStudentLookup = {
  "L1-1": ['Masataka',
    'Kairi',
    'Kaiko',
    'Minao',
    'Yui',
    'Ena',
    'Minoru',
    'Kota',],
  "L1-2": ['Sae',
    'Tomoko',
    'Kii',
    'Kyoko',
    'Sota',
    'Kanoko',
    'Hotaka',],
  "L1-3": ['Toshihiro',
    'Noritaka',
    'Akito',
    'Tokito',
    'Takao',
    'Hiroto',
    'Kaisei',],
  "L1-4": ['Ryoichi',
    'Junta',
    'Reon',
    'Chisako',
    'Masataka',
    'Kazunari',],
  "L2-1": ['Reiko',
    'Akari',
    'Ritsu',
    'Yura',
    'Kenshu',],
  "L2-2": ['Masaki',
    'Riko',
    'Kanade',
    'リクンタク',
    'Wakana',
    'Ririka',],
  "L2-3": ['Bill',
    'Yuya',
    'Ayano',
    'Sota',
    'Takushu',
    'Kiho',
    'Hana',],
  "L2-4": ['Rie',
    'Riku',
    'Itsuki',
    'イスマイル',
    'Leon',
    'Ryu',],
  "L2-5": ['Etsu',
    'Yugo',
    'Ryuki',
    'Sayuri',
    'Riko',],
  "L3-1": ['Akihiro',
    'Aiwa',
    'Kanma',
    'Sarah',
    'Keita',],
  "L3-2": ['Alex',
    'Koshi',
    'Sarah',
    'Itsuki',
    'Yuha',],
  "L3-3": ['Charles',
    'Yuto',
    'Tsuyoshi',
    'Lin',
    'Akari',
    'Kento',],
  "L3-4": ['Fudong',
    'Parvathi',
    'Hibiki',
    'リクンゴウ',
    'Moe',
    'Aran',
    'Rimi',],
  "L3-5": ['Makoto',
    'Mao',
    'Hiroaki',
    'Momoha',
    'Reika',
    'Aoi',],
  "L4-1": ['Kathy',
    'Sarah',
    'ミカレフアントニー',
    'Koharu',
    'Celina',
    'May',],
  "L4-2": ['Greg',
    'Nobuharu',
    'Ayato',
    'Niji',
    'Sara',
    'Akira',],
  "L4-3": ['Keen',
    'Haruka',
    'Ami',
    'Tamie',
    'Natsuko',
    'Tony',],
  "L4-4": ['Ashwin',
    'Ryuto',
    'Tisaki',
    'Yurie',
    'Hana',
    'Kazuma',],
  "L4-5": ['Praveen',
    'Taira',
    'Ren',
    'Tamaki',
    'Taiki',],
  "L4-6": ['Qingfei',
    'Kosuke',
    'Anna',
    'Kaito',
    'Ruka',
    'Karen',],
  "L4-7": ['Keith',
    'Momo',
    'Akira',
    'Sota',
    'Koharu',
    'Naomi',],
  "L4-8": ['Abigail',
    'Kyogo',
    'Kai',
    'Sharara',
    'Michelle',
    'Sara',],
  "L4-9": ['Dan',
    'Leina',
    'Takeshi',
    'Anjyu',
    'Wakana',
    'Lyra',
    'Yuta',],
  "L4-10": ['Luis',
    'Joshua',
    'Jacob',
    'Lyon',
    'Kotaro',
    'Mei',
    'Rowan',],
  "L4-11": ['Xiaoyu',
    'Riku',
    'Erin',
    'Kylie',
    'Junji',
    'Alex',
    'Kent',
    'Ray',
    'Darin',]
};

const testRoomStudentLookup = {
  'L1-1': [
    'Greg',
    'Tamago',
    'Yakiniku',
    'Asagohan',
  ],
  'L2-1': [
    'Tomoa Narasaki',
    'Meichi Narasaki',
    'Yoshiyuki Ogata',
    'Kokoro Fujii',
    'Keita Dohi',
  ],
  'L3-1': ['Yuto Horigome', 'Tony Hawk', 'Sean Malto']
}